spring:
  application:
    name: eureka-server8888
server:
  port: 8888

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/${spring.application.name}/
#    register-with-eureka: false
#    fetch-registry: false